# -*- mode: python ; coding: utf-8 -*-
"""Windows onefile build. UPX stays off to reduce antivirus false positives.

The version resource is generated by packaging/write_version_info.py.
oletools is collected whole because the scanner imports it only when a macro exists.
"""

from pathlib import Path

from PyInstaller.utils.hooks import collect_all, collect_submodules

root = Path(SPEC).resolve().parents[1]
entry = str(root / "packaging" / "entry.py")
version_file = str(root / "build" / "file_version_info.txt")
icon_file = str(root / "packaging" / "oculto-scan.ico")

datas = [
    (str(root / "src" / "oculto_scan" / "oculto-scan.png"), "oculto_scan"),
    (str(root / "src" / "oculto_scan" / "oculto-scan.ico"), "oculto_scan"),
]
binaries = []
hiddenimports = collect_submodules("oculto_scan")
for package in (
    "oletools",
    "olefile",
    "pcodedmp",
    "colorclass",
    "easygui",
    "msoffcrypto",
    "cryptography",
    "tarja",
    "defusedxml",
):
    package_datas, package_binaries, package_hidden = collect_all(package)
    datas += package_datas
    binaries += package_binaries
    hiddenimports += package_hidden

a = Analysis(
    [entry],
    pathex=[str(root / "src")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["pytest", "ruff"],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="oculto-scan",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version=version_file,
    icon=icon_file,
)
